language: python
before_script:
- pip install tox
- pip install -U requests"$REQUESTS_VERSION"

# test script
script:  tox -e ${TOX_ENV}
notifications:
  on_success: change
  on_failure: always

env:
  global:
  - TRAVIS_GH3="True"
  matrix:
  - TOX_ENV=py26 REQUESTS_VERSION="==2.0.1"
  - TOX_ENV=py27 REQUESTS_VERSION="==2.0.1"
  - TOX_ENV=py32 REQUESTS_VERSION="==2.0.1"
  - TOX_ENV=py33 REQUESTS_VERSION="==2.0.1"
  - TOX_ENV=py34 REQUESTS_VERSION="==2.0.1"
  - TOX_ENV=pypy REQUESTS_VERSION="==2.0.1"
  - TOX_ENV=py26 REQUESTS_VERSION=""
  - TOX_ENV=py27 REQUESTS_VERSION=""
  - TOX_ENV=py32 REQUESTS_VERSION=""
  - TOX_ENV=py33 REQUESTS_VERSION=""
  - TOX_ENV=py34 REQUESTS_VERSION=""
  - TOX_ENV=pypy REQUESTS_VERSION=""
  - TOX_ENV=py27-flake8
  - TOX_ENV=py34-flake8
  - TOX_ENV=docstrings
  - TOX_ENV=notebooks

matrix:
  fast_finish: true
  allow_failures:
  - env: TOX_ENV=docstrings

sudo: false
