language: python

before_script:
- pip install tox

# test script
script:  tox
notifications:
  on_success: change
  on_failure: always

env:
  global:
  - GH_RECORD_MODE='none'

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7 
      env: TOXENV=py37
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
    - python: nightly
      env: TOXENV=py38
      dist: xenial    # required for Python 3.8 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.8 (travis-ci/travis-ci#9069)
    - python: pypy
      env: TOXENV=pypy
    - python: 2.7
      env: TOXENV=py27-flake8
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
      env: TOXENV=py37-flake8
    - env: TOXENV=docstrings
    - env: TOXENV=notebooks
    - env: TOXENV=readme
    - env: TOXENV=doclint,docs
    - env: TOXENV=commitlint
  fast_finish: true
  allow_failures:
  - env: TOXENV=docstrings
  - env: TOXENV=notebooks

sudo: false
